// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ellipse_solver_ellipse_solver_Pipeline_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        outData_12_out,
        outData_12_out_ap_vld,
        outData_11_out,
        outData_11_out_ap_vld,
        outData_10_out,
        outData_10_out_ap_vld,
        outData_9_out,
        outData_9_out_ap_vld,
        outData_8_out,
        outData_8_out_ap_vld,
        outData_7_out,
        outData_7_out_ap_vld,
        outData_6_out,
        outData_6_out_ap_vld,
        outData_5_out,
        outData_5_out_ap_vld,
        outData_4_out,
        outData_4_out_ap_vld,
        outData_3_out,
        outData_3_out_ap_vld,
        outData_2_out,
        outData_2_out_ap_vld,
        outData_1_out,
        outData_1_out_ap_vld,
        outData_out,
        outData_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] outData_12_out;
output   outData_12_out_ap_vld;
output  [31:0] outData_11_out;
output   outData_11_out_ap_vld;
output  [31:0] outData_10_out;
output   outData_10_out_ap_vld;
output  [31:0] outData_9_out;
output   outData_9_out_ap_vld;
output  [31:0] outData_8_out;
output   outData_8_out_ap_vld;
output  [31:0] outData_7_out;
output   outData_7_out_ap_vld;
output  [31:0] outData_6_out;
output   outData_6_out_ap_vld;
output  [31:0] outData_5_out;
output   outData_5_out_ap_vld;
output  [31:0] outData_4_out;
output   outData_4_out_ap_vld;
output  [31:0] outData_3_out;
output   outData_3_out_ap_vld;
output  [31:0] outData_2_out;
output   outData_2_out_ap_vld;
output  [31:0] outData_1_out;
output   outData_1_out_ap_vld;
output  [31:0] outData_out;
output   outData_out_ap_vld;

reg ap_idle;
reg outData_12_out_ap_vld;
reg outData_11_out_ap_vld;
reg outData_10_out_ap_vld;
reg outData_9_out_ap_vld;
reg outData_8_out_ap_vld;
reg outData_7_out_ap_vld;
reg outData_6_out_ap_vld;
reg outData_5_out_ap_vld;
reg outData_4_out_ap_vld;
reg outData_3_out_ap_vld;
reg outData_2_out_ap_vld;
reg outData_1_out_ap_vld;
reg outData_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] exitcond473_fu_225_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [3:0] empty_fu_70;
wire   [3:0] empty_12_fu_231_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_p_load;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

ellipse_solver_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((exitcond473_fu_225_p2 == 1'd0)) begin
            empty_fu_70 <= empty_12_fu_231_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_70 <= 4'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_p_load = 4'd0;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_70;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_10_out_ap_vld = 1'b1;
    end else begin
        outData_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_11_out_ap_vld = 1'b1;
    end else begin
        outData_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_12_out_ap_vld = 1'b1;
    end else begin
        outData_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_1_out_ap_vld = 1'b1;
    end else begin
        outData_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_2_out_ap_vld = 1'b1;
    end else begin
        outData_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_3_out_ap_vld = 1'b1;
    end else begin
        outData_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_4_out_ap_vld = 1'b1;
    end else begin
        outData_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_5_out_ap_vld = 1'b1;
    end else begin
        outData_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_6_out_ap_vld = 1'b1;
    end else begin
        outData_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_7_out_ap_vld = 1'b1;
    end else begin
        outData_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_8_out_ap_vld = 1'b1;
    end else begin
        outData_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_9_out_ap_vld = 1'b1;
    end else begin
        outData_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond473_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        outData_out_ap_vld = 1'b1;
    end else begin
        outData_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_12_fu_231_p2 = (ap_sig_allocacmp_p_load + 4'd1);

assign exitcond473_fu_225_p2 = ((ap_sig_allocacmp_p_load == 4'd14) ? 1'b1 : 1'b0);

assign outData_10_out = 32'd0;

assign outData_11_out = 32'd0;

assign outData_12_out = 32'd0;

assign outData_1_out = 32'd0;

assign outData_2_out = 32'd0;

assign outData_3_out = 32'd0;

assign outData_4_out = 32'd0;

assign outData_5_out = 32'd0;

assign outData_6_out = 32'd0;

assign outData_7_out = 32'd0;

assign outData_8_out = 32'd0;

assign outData_9_out = 32'd0;

assign outData_out = 32'd0;

endmodule //ellipse_solver_ellipse_solver_Pipeline_1
