// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ellipse_solver_ellipse_solver_Pipeline_first_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dataPoints_address0,
        dataPoints_ce0,
        dataPoints_q0,
        dataHard_V_103_out,
        dataHard_V_103_out_ap_vld,
        dataHard_V_102_out,
        dataHard_V_102_out_ap_vld,
        dataHard_V_101_out,
        dataHard_V_101_out_ap_vld,
        dataHard_V_100_out,
        dataHard_V_100_out_ap_vld,
        dataHard_V_99_out,
        dataHard_V_99_out_ap_vld,
        dataHard_V_98_out,
        dataHard_V_98_out_ap_vld,
        dataHard_V_97_out,
        dataHard_V_97_out_ap_vld,
        dataHard_V_96_out,
        dataHard_V_96_out_ap_vld,
        dataHard_V_95_out,
        dataHard_V_95_out_ap_vld,
        dataHard_V_94_out,
        dataHard_V_94_out_ap_vld,
        dataHard_V_93_out,
        dataHard_V_93_out_ap_vld,
        dataHard_V_92_out,
        dataHard_V_92_out_ap_vld,
        dataHard_V_91_out,
        dataHard_V_91_out_ap_vld,
        dataHard_V_90_out,
        dataHard_V_90_out_ap_vld,
        dataHard_V_89_out,
        dataHard_V_89_out_ap_vld,
        dataHard_V_88_out,
        dataHard_V_88_out_ap_vld,
        dataHard_V_87_out,
        dataHard_V_87_out_ap_vld,
        dataHard_V_86_out,
        dataHard_V_86_out_ap_vld,
        dataHard_V_85_out,
        dataHard_V_85_out_ap_vld,
        dataHard_V_84_out,
        dataHard_V_84_out_ap_vld,
        dataHard_V_83_out,
        dataHard_V_83_out_ap_vld,
        dataHard_V_82_out,
        dataHard_V_82_out_ap_vld,
        dataHard_V_81_out,
        dataHard_V_81_out_ap_vld,
        dataHard_V_80_out,
        dataHard_V_80_out_ap_vld,
        dataHard_V_79_out,
        dataHard_V_79_out_ap_vld,
        dataHard_V_78_out,
        dataHard_V_78_out_ap_vld,
        dataHard_V_77_out,
        dataHard_V_77_out_ap_vld,
        dataHard_V_76_out,
        dataHard_V_76_out_ap_vld,
        dataHard_V_75_out,
        dataHard_V_75_out_ap_vld,
        dataHard_V_74_out,
        dataHard_V_74_out_ap_vld,
        dataHard_V_73_out,
        dataHard_V_73_out_ap_vld,
        dataHard_V_72_out,
        dataHard_V_72_out_ap_vld,
        dataHard_V_71_out,
        dataHard_V_71_out_ap_vld,
        dataHard_V_70_out,
        dataHard_V_70_out_ap_vld,
        dataHard_V_69_out,
        dataHard_V_69_out_ap_vld,
        dataHard_V_68_out,
        dataHard_V_68_out_ap_vld,
        dataHard_V_67_out,
        dataHard_V_67_out_ap_vld,
        dataHard_V_66_out,
        dataHard_V_66_out_ap_vld,
        dataHard_V_65_out,
        dataHard_V_65_out_ap_vld,
        dataHard_V_64_out,
        dataHard_V_64_out_ap_vld,
        dataHard_V_63_out,
        dataHard_V_63_out_ap_vld,
        dataHard_V_62_out,
        dataHard_V_62_out_ap_vld,
        dataHard_V_61_out,
        dataHard_V_61_out_ap_vld,
        dataHard_V_60_out,
        dataHard_V_60_out_ap_vld,
        dataHard_V_59_out,
        dataHard_V_59_out_ap_vld,
        dataHard_V_58_out,
        dataHard_V_58_out_ap_vld,
        dataHard_V_57_out,
        dataHard_V_57_out_ap_vld,
        dataHard_V_56_out,
        dataHard_V_56_out_ap_vld,
        dataHard_V_55_out,
        dataHard_V_55_out_ap_vld,
        dataHard_V_54_out,
        dataHard_V_54_out_ap_vld,
        dataHard_V_53_out,
        dataHard_V_53_out_ap_vld,
        dataHard_V_52_out,
        dataHard_V_52_out_ap_vld,
        dataHard_V_51_out,
        dataHard_V_51_out_ap_vld,
        dataHard_V_50_out,
        dataHard_V_50_out_ap_vld,
        dataHard_V_49_out,
        dataHard_V_49_out_ap_vld,
        dataHard_V_48_out,
        dataHard_V_48_out_ap_vld,
        dataHard_V_47_out,
        dataHard_V_47_out_ap_vld,
        dataHard_V_46_out,
        dataHard_V_46_out_ap_vld,
        dataHard_V_45_out,
        dataHard_V_45_out_ap_vld,
        dataHard_V_44_out,
        dataHard_V_44_out_ap_vld,
        dataHard_V_43_out,
        dataHard_V_43_out_ap_vld,
        dataHard_V_42_out,
        dataHard_V_42_out_ap_vld,
        dataHard_V_41_out,
        dataHard_V_41_out_ap_vld,
        dataHard_V_40_out,
        dataHard_V_40_out_ap_vld,
        dataHard_V_39_out,
        dataHard_V_39_out_ap_vld,
        dataHard_V_38_out,
        dataHard_V_38_out_ap_vld,
        dataHard_V_37_out,
        dataHard_V_37_out_ap_vld,
        dataHard_V_36_out,
        dataHard_V_36_out_ap_vld,
        dataHard_V_35_out,
        dataHard_V_35_out_ap_vld,
        dataHard_V_34_out,
        dataHard_V_34_out_ap_vld,
        dataHard_V_33_out,
        dataHard_V_33_out_ap_vld,
        dataHard_V_32_out,
        dataHard_V_32_out_ap_vld,
        dataHard_V_31_out,
        dataHard_V_31_out_ap_vld,
        dataHard_V_30_out,
        dataHard_V_30_out_ap_vld,
        dataHard_V_29_out,
        dataHard_V_29_out_ap_vld,
        dataHard_V_28_out,
        dataHard_V_28_out_ap_vld,
        dataHard_V_27_out,
        dataHard_V_27_out_ap_vld,
        dataHard_V_26_out,
        dataHard_V_26_out_ap_vld,
        dataHard_V_25_out,
        dataHard_V_25_out_ap_vld,
        dataHard_V_24_out,
        dataHard_V_24_out_ap_vld,
        dataHard_V_23_out,
        dataHard_V_23_out_ap_vld,
        dataHard_V_22_out,
        dataHard_V_22_out_ap_vld,
        dataHard_V_21_out,
        dataHard_V_21_out_ap_vld,
        dataHard_V_20_out,
        dataHard_V_20_out_ap_vld,
        dataHard_V_19_out,
        dataHard_V_19_out_ap_vld,
        dataHard_V_18_out,
        dataHard_V_18_out_ap_vld,
        dataHard_V_17_out,
        dataHard_V_17_out_ap_vld,
        dataHard_V_16_out,
        dataHard_V_16_out_ap_vld,
        dataHard_V_15_out,
        dataHard_V_15_out_ap_vld,
        dataHard_V_14_out,
        dataHard_V_14_out_ap_vld,
        dataHard_V_13_out,
        dataHard_V_13_out_ap_vld,
        dataHard_V_12_out,
        dataHard_V_12_out_ap_vld,
        dataHard_V_11_out,
        dataHard_V_11_out_ap_vld,
        dataHard_V_10_out,
        dataHard_V_10_out_ap_vld,
        dataHard_V_9_out,
        dataHard_V_9_out_ap_vld,
        dataHard_V_8_out,
        dataHard_V_8_out_ap_vld,
        dataHard_V_7_out,
        dataHard_V_7_out_ap_vld,
        dataHard_V_6_out,
        dataHard_V_6_out_ap_vld,
        dataHard_V_5_out,
        dataHard_V_5_out_ap_vld,
        dataHard_V_4_out,
        dataHard_V_4_out_ap_vld,
        dataHard_V_3_out,
        dataHard_V_3_out_ap_vld,
        dataHard_V_2_out,
        dataHard_V_2_out_ap_vld,
        dataHard_V_1_out,
        dataHard_V_1_out_ap_vld,
        dataHard_V_out,
        dataHard_V_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] dataPoints_address0;
output   dataPoints_ce0;
input  [63:0] dataPoints_q0;
output  [31:0] dataHard_V_103_out;
output   dataHard_V_103_out_ap_vld;
output  [31:0] dataHard_V_102_out;
output   dataHard_V_102_out_ap_vld;
output  [31:0] dataHard_V_101_out;
output   dataHard_V_101_out_ap_vld;
output  [31:0] dataHard_V_100_out;
output   dataHard_V_100_out_ap_vld;
output  [31:0] dataHard_V_99_out;
output   dataHard_V_99_out_ap_vld;
output  [31:0] dataHard_V_98_out;
output   dataHard_V_98_out_ap_vld;
output  [31:0] dataHard_V_97_out;
output   dataHard_V_97_out_ap_vld;
output  [31:0] dataHard_V_96_out;
output   dataHard_V_96_out_ap_vld;
output  [31:0] dataHard_V_95_out;
output   dataHard_V_95_out_ap_vld;
output  [31:0] dataHard_V_94_out;
output   dataHard_V_94_out_ap_vld;
output  [31:0] dataHard_V_93_out;
output   dataHard_V_93_out_ap_vld;
output  [31:0] dataHard_V_92_out;
output   dataHard_V_92_out_ap_vld;
output  [31:0] dataHard_V_91_out;
output   dataHard_V_91_out_ap_vld;
output  [31:0] dataHard_V_90_out;
output   dataHard_V_90_out_ap_vld;
output  [31:0] dataHard_V_89_out;
output   dataHard_V_89_out_ap_vld;
output  [31:0] dataHard_V_88_out;
output   dataHard_V_88_out_ap_vld;
output  [31:0] dataHard_V_87_out;
output   dataHard_V_87_out_ap_vld;
output  [31:0] dataHard_V_86_out;
output   dataHard_V_86_out_ap_vld;
output  [31:0] dataHard_V_85_out;
output   dataHard_V_85_out_ap_vld;
output  [31:0] dataHard_V_84_out;
output   dataHard_V_84_out_ap_vld;
output  [31:0] dataHard_V_83_out;
output   dataHard_V_83_out_ap_vld;
output  [31:0] dataHard_V_82_out;
output   dataHard_V_82_out_ap_vld;
output  [31:0] dataHard_V_81_out;
output   dataHard_V_81_out_ap_vld;
output  [31:0] dataHard_V_80_out;
output   dataHard_V_80_out_ap_vld;
output  [31:0] dataHard_V_79_out;
output   dataHard_V_79_out_ap_vld;
output  [31:0] dataHard_V_78_out;
output   dataHard_V_78_out_ap_vld;
output  [31:0] dataHard_V_77_out;
output   dataHard_V_77_out_ap_vld;
output  [31:0] dataHard_V_76_out;
output   dataHard_V_76_out_ap_vld;
output  [31:0] dataHard_V_75_out;
output   dataHard_V_75_out_ap_vld;
output  [31:0] dataHard_V_74_out;
output   dataHard_V_74_out_ap_vld;
output  [31:0] dataHard_V_73_out;
output   dataHard_V_73_out_ap_vld;
output  [31:0] dataHard_V_72_out;
output   dataHard_V_72_out_ap_vld;
output  [31:0] dataHard_V_71_out;
output   dataHard_V_71_out_ap_vld;
output  [31:0] dataHard_V_70_out;
output   dataHard_V_70_out_ap_vld;
output  [31:0] dataHard_V_69_out;
output   dataHard_V_69_out_ap_vld;
output  [31:0] dataHard_V_68_out;
output   dataHard_V_68_out_ap_vld;
output  [31:0] dataHard_V_67_out;
output   dataHard_V_67_out_ap_vld;
output  [31:0] dataHard_V_66_out;
output   dataHard_V_66_out_ap_vld;
output  [31:0] dataHard_V_65_out;
output   dataHard_V_65_out_ap_vld;
output  [31:0] dataHard_V_64_out;
output   dataHard_V_64_out_ap_vld;
output  [31:0] dataHard_V_63_out;
output   dataHard_V_63_out_ap_vld;
output  [31:0] dataHard_V_62_out;
output   dataHard_V_62_out_ap_vld;
output  [31:0] dataHard_V_61_out;
output   dataHard_V_61_out_ap_vld;
output  [31:0] dataHard_V_60_out;
output   dataHard_V_60_out_ap_vld;
output  [31:0] dataHard_V_59_out;
output   dataHard_V_59_out_ap_vld;
output  [31:0] dataHard_V_58_out;
output   dataHard_V_58_out_ap_vld;
output  [31:0] dataHard_V_57_out;
output   dataHard_V_57_out_ap_vld;
output  [31:0] dataHard_V_56_out;
output   dataHard_V_56_out_ap_vld;
output  [31:0] dataHard_V_55_out;
output   dataHard_V_55_out_ap_vld;
output  [31:0] dataHard_V_54_out;
output   dataHard_V_54_out_ap_vld;
output  [31:0] dataHard_V_53_out;
output   dataHard_V_53_out_ap_vld;
output  [31:0] dataHard_V_52_out;
output   dataHard_V_52_out_ap_vld;
output  [31:0] dataHard_V_51_out;
output   dataHard_V_51_out_ap_vld;
output  [31:0] dataHard_V_50_out;
output   dataHard_V_50_out_ap_vld;
output  [31:0] dataHard_V_49_out;
output   dataHard_V_49_out_ap_vld;
output  [31:0] dataHard_V_48_out;
output   dataHard_V_48_out_ap_vld;
output  [31:0] dataHard_V_47_out;
output   dataHard_V_47_out_ap_vld;
output  [31:0] dataHard_V_46_out;
output   dataHard_V_46_out_ap_vld;
output  [31:0] dataHard_V_45_out;
output   dataHard_V_45_out_ap_vld;
output  [31:0] dataHard_V_44_out;
output   dataHard_V_44_out_ap_vld;
output  [31:0] dataHard_V_43_out;
output   dataHard_V_43_out_ap_vld;
output  [31:0] dataHard_V_42_out;
output   dataHard_V_42_out_ap_vld;
output  [31:0] dataHard_V_41_out;
output   dataHard_V_41_out_ap_vld;
output  [31:0] dataHard_V_40_out;
output   dataHard_V_40_out_ap_vld;
output  [31:0] dataHard_V_39_out;
output   dataHard_V_39_out_ap_vld;
output  [31:0] dataHard_V_38_out;
output   dataHard_V_38_out_ap_vld;
output  [31:0] dataHard_V_37_out;
output   dataHard_V_37_out_ap_vld;
output  [31:0] dataHard_V_36_out;
output   dataHard_V_36_out_ap_vld;
output  [31:0] dataHard_V_35_out;
output   dataHard_V_35_out_ap_vld;
output  [31:0] dataHard_V_34_out;
output   dataHard_V_34_out_ap_vld;
output  [31:0] dataHard_V_33_out;
output   dataHard_V_33_out_ap_vld;
output  [31:0] dataHard_V_32_out;
output   dataHard_V_32_out_ap_vld;
output  [31:0] dataHard_V_31_out;
output   dataHard_V_31_out_ap_vld;
output  [31:0] dataHard_V_30_out;
output   dataHard_V_30_out_ap_vld;
output  [31:0] dataHard_V_29_out;
output   dataHard_V_29_out_ap_vld;
output  [31:0] dataHard_V_28_out;
output   dataHard_V_28_out_ap_vld;
output  [31:0] dataHard_V_27_out;
output   dataHard_V_27_out_ap_vld;
output  [31:0] dataHard_V_26_out;
output   dataHard_V_26_out_ap_vld;
output  [31:0] dataHard_V_25_out;
output   dataHard_V_25_out_ap_vld;
output  [31:0] dataHard_V_24_out;
output   dataHard_V_24_out_ap_vld;
output  [31:0] dataHard_V_23_out;
output   dataHard_V_23_out_ap_vld;
output  [31:0] dataHard_V_22_out;
output   dataHard_V_22_out_ap_vld;
output  [31:0] dataHard_V_21_out;
output   dataHard_V_21_out_ap_vld;
output  [31:0] dataHard_V_20_out;
output   dataHard_V_20_out_ap_vld;
output  [31:0] dataHard_V_19_out;
output   dataHard_V_19_out_ap_vld;
output  [31:0] dataHard_V_18_out;
output   dataHard_V_18_out_ap_vld;
output  [31:0] dataHard_V_17_out;
output   dataHard_V_17_out_ap_vld;
output  [31:0] dataHard_V_16_out;
output   dataHard_V_16_out_ap_vld;
output  [31:0] dataHard_V_15_out;
output   dataHard_V_15_out_ap_vld;
output  [31:0] dataHard_V_14_out;
output   dataHard_V_14_out_ap_vld;
output  [31:0] dataHard_V_13_out;
output   dataHard_V_13_out_ap_vld;
output  [31:0] dataHard_V_12_out;
output   dataHard_V_12_out_ap_vld;
output  [31:0] dataHard_V_11_out;
output   dataHard_V_11_out_ap_vld;
output  [31:0] dataHard_V_10_out;
output   dataHard_V_10_out_ap_vld;
output  [31:0] dataHard_V_9_out;
output   dataHard_V_9_out_ap_vld;
output  [31:0] dataHard_V_8_out;
output   dataHard_V_8_out_ap_vld;
output  [31:0] dataHard_V_7_out;
output   dataHard_V_7_out_ap_vld;
output  [31:0] dataHard_V_6_out;
output   dataHard_V_6_out_ap_vld;
output  [31:0] dataHard_V_5_out;
output   dataHard_V_5_out_ap_vld;
output  [31:0] dataHard_V_4_out;
output   dataHard_V_4_out_ap_vld;
output  [31:0] dataHard_V_3_out;
output   dataHard_V_3_out_ap_vld;
output  [31:0] dataHard_V_2_out;
output   dataHard_V_2_out_ap_vld;
output  [31:0] dataHard_V_1_out;
output   dataHard_V_1_out_ap_vld;
output  [31:0] dataHard_V_out;
output   dataHard_V_out_ap_vld;

reg ap_idle;
reg dataPoints_ce0;
reg dataHard_V_103_out_ap_vld;
reg dataHard_V_102_out_ap_vld;
reg dataHard_V_101_out_ap_vld;
reg dataHard_V_100_out_ap_vld;
reg dataHard_V_99_out_ap_vld;
reg dataHard_V_98_out_ap_vld;
reg dataHard_V_97_out_ap_vld;
reg dataHard_V_96_out_ap_vld;
reg dataHard_V_95_out_ap_vld;
reg dataHard_V_94_out_ap_vld;
reg dataHard_V_93_out_ap_vld;
reg dataHard_V_92_out_ap_vld;
reg dataHard_V_91_out_ap_vld;
reg dataHard_V_90_out_ap_vld;
reg dataHard_V_89_out_ap_vld;
reg dataHard_V_88_out_ap_vld;
reg dataHard_V_87_out_ap_vld;
reg dataHard_V_86_out_ap_vld;
reg dataHard_V_85_out_ap_vld;
reg dataHard_V_84_out_ap_vld;
reg dataHard_V_83_out_ap_vld;
reg dataHard_V_82_out_ap_vld;
reg dataHard_V_81_out_ap_vld;
reg dataHard_V_80_out_ap_vld;
reg dataHard_V_79_out_ap_vld;
reg dataHard_V_78_out_ap_vld;
reg dataHard_V_77_out_ap_vld;
reg dataHard_V_76_out_ap_vld;
reg dataHard_V_75_out_ap_vld;
reg dataHard_V_74_out_ap_vld;
reg dataHard_V_73_out_ap_vld;
reg dataHard_V_72_out_ap_vld;
reg dataHard_V_71_out_ap_vld;
reg dataHard_V_70_out_ap_vld;
reg dataHard_V_69_out_ap_vld;
reg dataHard_V_68_out_ap_vld;
reg dataHard_V_67_out_ap_vld;
reg dataHard_V_66_out_ap_vld;
reg dataHard_V_65_out_ap_vld;
reg dataHard_V_64_out_ap_vld;
reg dataHard_V_63_out_ap_vld;
reg dataHard_V_62_out_ap_vld;
reg dataHard_V_61_out_ap_vld;
reg dataHard_V_60_out_ap_vld;
reg dataHard_V_59_out_ap_vld;
reg dataHard_V_58_out_ap_vld;
reg dataHard_V_57_out_ap_vld;
reg dataHard_V_56_out_ap_vld;
reg dataHard_V_55_out_ap_vld;
reg dataHard_V_54_out_ap_vld;
reg dataHard_V_53_out_ap_vld;
reg dataHard_V_52_out_ap_vld;
reg dataHard_V_51_out_ap_vld;
reg dataHard_V_50_out_ap_vld;
reg dataHard_V_49_out_ap_vld;
reg dataHard_V_48_out_ap_vld;
reg dataHard_V_47_out_ap_vld;
reg dataHard_V_46_out_ap_vld;
reg dataHard_V_45_out_ap_vld;
reg dataHard_V_44_out_ap_vld;
reg dataHard_V_43_out_ap_vld;
reg dataHard_V_42_out_ap_vld;
reg dataHard_V_41_out_ap_vld;
reg dataHard_V_40_out_ap_vld;
reg dataHard_V_39_out_ap_vld;
reg dataHard_V_38_out_ap_vld;
reg dataHard_V_37_out_ap_vld;
reg dataHard_V_36_out_ap_vld;
reg dataHard_V_35_out_ap_vld;
reg dataHard_V_34_out_ap_vld;
reg dataHard_V_33_out_ap_vld;
reg dataHard_V_32_out_ap_vld;
reg dataHard_V_31_out_ap_vld;
reg dataHard_V_30_out_ap_vld;
reg dataHard_V_29_out_ap_vld;
reg dataHard_V_28_out_ap_vld;
reg dataHard_V_27_out_ap_vld;
reg dataHard_V_26_out_ap_vld;
reg dataHard_V_25_out_ap_vld;
reg dataHard_V_24_out_ap_vld;
reg dataHard_V_23_out_ap_vld;
reg dataHard_V_22_out_ap_vld;
reg dataHard_V_21_out_ap_vld;
reg dataHard_V_20_out_ap_vld;
reg dataHard_V_19_out_ap_vld;
reg dataHard_V_18_out_ap_vld;
reg dataHard_V_17_out_ap_vld;
reg dataHard_V_16_out_ap_vld;
reg dataHard_V_15_out_ap_vld;
reg dataHard_V_14_out_ap_vld;
reg dataHard_V_13_out_ap_vld;
reg dataHard_V_12_out_ap_vld;
reg dataHard_V_11_out_ap_vld;
reg dataHard_V_10_out_ap_vld;
reg dataHard_V_9_out_ap_vld;
reg dataHard_V_8_out_ap_vld;
reg dataHard_V_7_out_ap_vld;
reg dataHard_V_6_out_ap_vld;
reg dataHard_V_5_out_ap_vld;
reg dataHard_V_4_out_ap_vld;
reg dataHard_V_3_out_ap_vld;
reg dataHard_V_2_out_ap_vld;
reg dataHard_V_1_out_ap_vld;
reg dataHard_V_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln20_fu_1436_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln20_reg_3063;
wire   [2:0] trunc_ln22_fu_1453_p1;
reg   [2:0] trunc_ln22_reg_3072;
reg   [2:0] trunc_ln22_reg_3072_pp0_iter1_reg;
wire  signed [31:0] dataHard_V_104_fu_1462_p1;
reg  signed [31:0] dataHard_V_104_reg_3076;
wire  signed [31:0] dataHard_V_105_fu_1466_p2;
reg  signed [31:0] dataHard_V_105_reg_3092;
reg  signed [31:0] dataHard_V_111_reg_3107;
wire  signed [31:0] dataHard_V_118_fu_1482_p2;
reg  signed [31:0] dataHard_V_118_reg_3124;
wire   [63:0] zext_ln20_fu_1448_p1;
wire    ap_block_pp0_stage0;
reg   [3:0] i_fu_262;
wire   [3:0] add_ln20_fu_1442_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_2;
reg   [31:0] dataHard_V_fu_266;
reg   [31:0] dataHard_V_1_fu_270;
reg   [31:0] dataHard_V_2_fu_274;
wire   [31:0] dataHard_V_117_fu_1492_p2;
reg   [31:0] dataHard_V_3_fu_278;
reg   [31:0] dataHard_V_4_fu_282;
reg   [31:0] dataHard_V_5_fu_286;
wire   [31:0] dataHard_V_119_fu_1496_p2;
reg   [31:0] dataHard_V_6_fu_290;
wire   [31:0] dataHard_V_120_fu_1500_p2;
reg   [31:0] dataHard_V_7_fu_294;
wire  signed [31:0] dataHard_V_107_fu_1488_p2;
reg   [31:0] dataHard_V_8_fu_298;
wire  signed [31:0] dataHard_V_121_fu_1504_p2;
reg   [31:0] dataHard_V_9_fu_302;
wire   [31:0] dataHard_V_122_fu_1508_p2;
reg   [31:0] dataHard_V_10_fu_306;
wire   [31:0] dataHard_V_123_fu_1512_p2;
reg   [31:0] dataHard_V_11_fu_310;
wire   [31:0] dataHard_V_124_fu_1517_p2;
reg   [31:0] dataHard_V_12_fu_314;
wire   [31:0] dataHard_V_125_fu_1522_p2;
reg   [31:0] dataHard_V_13_fu_318;
reg   [31:0] dataHard_V_14_fu_322;
reg   [31:0] dataHard_V_15_fu_326;
reg   [31:0] dataHard_V_16_fu_330;
reg   [31:0] dataHard_V_17_fu_334;
reg   [31:0] dataHard_V_18_fu_338;
reg   [31:0] dataHard_V_19_fu_342;
reg   [31:0] dataHard_V_20_fu_346;
reg   [31:0] dataHard_V_21_fu_350;
reg   [31:0] dataHard_V_22_fu_354;
reg   [31:0] dataHard_V_23_fu_358;
reg   [31:0] dataHard_V_24_fu_362;
reg   [31:0] dataHard_V_25_fu_366;
reg   [31:0] dataHard_V_26_fu_370;
reg   [31:0] dataHard_V_27_fu_374;
reg   [31:0] dataHard_V_28_fu_378;
reg   [31:0] dataHard_V_29_fu_382;
reg   [31:0] dataHard_V_30_fu_386;
reg   [31:0] dataHard_V_31_fu_390;
reg   [31:0] dataHard_V_32_fu_394;
reg   [31:0] dataHard_V_33_fu_398;
reg   [31:0] dataHard_V_34_fu_402;
reg   [31:0] dataHard_V_35_fu_406;
reg   [31:0] dataHard_V_36_fu_410;
reg   [31:0] dataHard_V_37_fu_414;
reg   [31:0] dataHard_V_38_fu_418;
reg   [31:0] dataHard_V_39_fu_422;
reg   [31:0] dataHard_V_40_fu_426;
reg   [31:0] dataHard_V_41_fu_430;
reg   [31:0] dataHard_V_42_fu_434;
reg   [31:0] dataHard_V_43_fu_438;
reg   [31:0] dataHard_V_44_fu_442;
reg   [31:0] dataHard_V_45_fu_446;
reg   [31:0] dataHard_V_46_fu_450;
reg   [31:0] dataHard_V_47_fu_454;
reg   [31:0] dataHard_V_48_fu_458;
reg   [31:0] dataHard_V_49_fu_462;
reg   [31:0] dataHard_V_50_fu_466;
reg   [31:0] dataHard_V_51_fu_470;
reg   [31:0] dataHard_V_52_fu_474;
reg   [31:0] dataHard_V_53_fu_478;
reg   [31:0] dataHard_V_54_fu_482;
reg   [31:0] dataHard_V_55_fu_486;
reg   [31:0] dataHard_V_56_fu_490;
reg   [31:0] dataHard_V_57_fu_494;
reg   [31:0] dataHard_V_58_fu_498;
reg   [31:0] dataHard_V_59_fu_502;
reg   [31:0] dataHard_V_60_fu_506;
reg   [31:0] dataHard_V_61_fu_510;
reg   [31:0] dataHard_V_62_fu_514;
reg   [31:0] dataHard_V_63_fu_518;
reg   [31:0] dataHard_V_64_fu_522;
reg   [31:0] dataHard_V_65_fu_526;
reg   [31:0] dataHard_V_66_fu_530;
reg   [31:0] dataHard_V_67_fu_534;
reg   [31:0] dataHard_V_68_fu_538;
reg   [31:0] dataHard_V_69_fu_542;
reg   [31:0] dataHard_V_70_fu_546;
reg   [31:0] dataHard_V_71_fu_550;
reg   [31:0] dataHard_V_72_fu_554;
reg   [31:0] dataHard_V_73_fu_558;
reg   [31:0] dataHard_V_74_fu_562;
reg   [31:0] dataHard_V_75_fu_566;
reg   [31:0] dataHard_V_76_fu_570;
reg   [31:0] dataHard_V_77_fu_574;
reg   [31:0] dataHard_V_78_fu_578;
reg   [31:0] dataHard_V_79_fu_582;
reg   [31:0] dataHard_V_80_fu_586;
reg   [31:0] dataHard_V_81_fu_590;
reg   [31:0] dataHard_V_82_fu_594;
reg   [31:0] dataHard_V_83_fu_598;
reg   [31:0] dataHard_V_84_fu_602;
reg   [31:0] dataHard_V_85_fu_606;
reg   [31:0] dataHard_V_86_fu_610;
reg   [31:0] dataHard_V_87_fu_614;
reg   [31:0] dataHard_V_88_fu_618;
reg   [31:0] dataHard_V_89_fu_622;
reg   [31:0] dataHard_V_90_fu_626;
reg   [31:0] dataHard_V_91_fu_630;
reg   [31:0] dataHard_V_92_fu_634;
reg   [31:0] dataHard_V_93_fu_638;
reg   [31:0] dataHard_V_94_fu_642;
reg   [31:0] dataHard_V_95_fu_646;
reg   [31:0] dataHard_V_96_fu_650;
reg   [31:0] dataHard_V_97_fu_654;
reg   [31:0] dataHard_V_98_fu_658;
reg   [31:0] dataHard_V_99_fu_662;
reg   [31:0] dataHard_V_100_fu_666;
reg   [31:0] dataHard_V_101_fu_670;
reg   [31:0] dataHard_V_102_fu_674;
reg   [31:0] dataHard_V_103_fu_678;
wire    ap_block_pp0_stage0_01001;
wire  signed [31:0] dataHard_V_118_fu_1482_p0;
wire  signed [31:0] dataHard_V_118_fu_1482_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U14(
    .din0(dataHard_V_104_fu_1462_p1),
    .din1(dataHard_V_104_fu_1462_p1),
    .dout(dataHard_V_105_fu_1466_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U15(
    .din0(dataHard_V_118_fu_1482_p0),
    .din1(dataHard_V_118_fu_1482_p1),
    .dout(dataHard_V_118_fu_1482_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U16(
    .din0(dataHard_V_105_reg_3092),
    .din1(dataHard_V_104_reg_3076),
    .dout(dataHard_V_107_fu_1488_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U17(
    .din0(dataHard_V_111_reg_3107),
    .din1(dataHard_V_104_reg_3076),
    .dout(dataHard_V_117_fu_1492_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U18(
    .din0(dataHard_V_105_reg_3092),
    .din1(dataHard_V_111_reg_3107),
    .dout(dataHard_V_119_fu_1496_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U19(
    .din0(dataHard_V_118_reg_3124),
    .din1(dataHard_V_104_reg_3076),
    .dout(dataHard_V_120_fu_1500_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U20(
    .din0(dataHard_V_118_reg_3124),
    .din1(dataHard_V_111_reg_3107),
    .dout(dataHard_V_121_fu_1504_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U21(
    .din0(dataHard_V_118_reg_3124),
    .din1(dataHard_V_105_reg_3092),
    .dout(dataHard_V_122_fu_1508_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U22(
    .din0(dataHard_V_107_fu_1488_p2),
    .din1(dataHard_V_111_reg_3107),
    .dout(dataHard_V_123_fu_1512_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U23(
    .din0(dataHard_V_121_fu_1504_p2),
    .din1(dataHard_V_104_reg_3076),
    .dout(dataHard_V_124_fu_1517_p2)
);

ellipse_solver_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U24(
    .din0(dataHard_V_121_fu_1504_p2),
    .din1(dataHard_V_111_reg_3107),
    .dout(dataHard_V_125_fu_1522_p2)
);

ellipse_solver_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dataHard_V_fu_266 <= 32'd0;
        end else if (((trunc_ln22_reg_3072_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            dataHard_V_fu_266 <= dataHard_V_104_reg_3076;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln20_fu_1436_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_262 <= add_ln20_fu_1442_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_262 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        dataHard_V_104_reg_3076 <= dataHard_V_104_fu_1462_p1;
        dataHard_V_105_reg_3092 <= dataHard_V_105_fu_1466_p2;
        dataHard_V_111_reg_3107 <= {{dataPoints_q0[63:32]}};
        dataHard_V_118_reg_3124 <= dataHard_V_118_fu_1482_p2;
        icmp_ln20_reg_3063 <= icmp_ln20_fu_1436_p2;
        trunc_ln22_reg_3072_pp0_iter1_reg <= trunc_ln22_reg_3072;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln22_reg_3072_pp0_iter1_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dataHard_V_100_fu_666 <= dataHard_V_122_fu_1508_p2;
        dataHard_V_101_fu_670 <= dataHard_V_123_fu_1512_p2;
        dataHard_V_102_fu_674 <= dataHard_V_124_fu_1517_p2;
        dataHard_V_103_fu_678 <= dataHard_V_125_fu_1522_p2;
        dataHard_V_91_fu_630 <= dataHard_V_104_reg_3076;
        dataHard_V_92_fu_634 <= dataHard_V_111_reg_3107;
        dataHard_V_93_fu_638 <= dataHard_V_117_fu_1492_p2;
        dataHard_V_94_fu_642 <= dataHard_V_105_reg_3092;
        dataHard_V_95_fu_646 <= dataHard_V_118_reg_3124;
        dataHard_V_96_fu_650 <= dataHard_V_119_fu_1496_p2;
        dataHard_V_97_fu_654 <= dataHard_V_120_fu_1500_p2;
        dataHard_V_98_fu_658 <= dataHard_V_107_fu_1488_p2;
        dataHard_V_99_fu_662 <= dataHard_V_121_fu_1504_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln22_reg_3072_pp0_iter1_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dataHard_V_10_fu_306 <= dataHard_V_123_fu_1512_p2;
        dataHard_V_11_fu_310 <= dataHard_V_124_fu_1517_p2;
        dataHard_V_12_fu_314 <= dataHard_V_125_fu_1522_p2;
        dataHard_V_1_fu_270 <= dataHard_V_111_reg_3107;
        dataHard_V_2_fu_274 <= dataHard_V_117_fu_1492_p2;
        dataHard_V_3_fu_278 <= dataHard_V_105_reg_3092;
        dataHard_V_4_fu_282 <= dataHard_V_118_reg_3124;
        dataHard_V_5_fu_286 <= dataHard_V_119_fu_1496_p2;
        dataHard_V_6_fu_290 <= dataHard_V_120_fu_1500_p2;
        dataHard_V_7_fu_294 <= dataHard_V_107_fu_1488_p2;
        dataHard_V_8_fu_298 <= dataHard_V_121_fu_1504_p2;
        dataHard_V_9_fu_302 <= dataHard_V_122_fu_1508_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln22_reg_3072_pp0_iter1_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dataHard_V_13_fu_318 <= dataHard_V_104_reg_3076;
        dataHard_V_14_fu_322 <= dataHard_V_111_reg_3107;
        dataHard_V_15_fu_326 <= dataHard_V_117_fu_1492_p2;
        dataHard_V_16_fu_330 <= dataHard_V_105_reg_3092;
        dataHard_V_17_fu_334 <= dataHard_V_118_reg_3124;
        dataHard_V_18_fu_338 <= dataHard_V_119_fu_1496_p2;
        dataHard_V_19_fu_342 <= dataHard_V_120_fu_1500_p2;
        dataHard_V_20_fu_346 <= dataHard_V_107_fu_1488_p2;
        dataHard_V_21_fu_350 <= dataHard_V_121_fu_1504_p2;
        dataHard_V_22_fu_354 <= dataHard_V_122_fu_1508_p2;
        dataHard_V_23_fu_358 <= dataHard_V_123_fu_1512_p2;
        dataHard_V_24_fu_362 <= dataHard_V_124_fu_1517_p2;
        dataHard_V_25_fu_366 <= dataHard_V_125_fu_1522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln22_reg_3072_pp0_iter1_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dataHard_V_26_fu_370 <= dataHard_V_104_reg_3076;
        dataHard_V_27_fu_374 <= dataHard_V_111_reg_3107;
        dataHard_V_28_fu_378 <= dataHard_V_117_fu_1492_p2;
        dataHard_V_29_fu_382 <= dataHard_V_105_reg_3092;
        dataHard_V_30_fu_386 <= dataHard_V_118_reg_3124;
        dataHard_V_31_fu_390 <= dataHard_V_119_fu_1496_p2;
        dataHard_V_32_fu_394 <= dataHard_V_120_fu_1500_p2;
        dataHard_V_33_fu_398 <= dataHard_V_107_fu_1488_p2;
        dataHard_V_34_fu_402 <= dataHard_V_121_fu_1504_p2;
        dataHard_V_35_fu_406 <= dataHard_V_122_fu_1508_p2;
        dataHard_V_36_fu_410 <= dataHard_V_123_fu_1512_p2;
        dataHard_V_37_fu_414 <= dataHard_V_124_fu_1517_p2;
        dataHard_V_38_fu_418 <= dataHard_V_125_fu_1522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln22_reg_3072_pp0_iter1_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dataHard_V_39_fu_422 <= dataHard_V_104_reg_3076;
        dataHard_V_40_fu_426 <= dataHard_V_111_reg_3107;
        dataHard_V_41_fu_430 <= dataHard_V_117_fu_1492_p2;
        dataHard_V_42_fu_434 <= dataHard_V_105_reg_3092;
        dataHard_V_43_fu_438 <= dataHard_V_118_reg_3124;
        dataHard_V_44_fu_442 <= dataHard_V_119_fu_1496_p2;
        dataHard_V_45_fu_446 <= dataHard_V_120_fu_1500_p2;
        dataHard_V_46_fu_450 <= dataHard_V_107_fu_1488_p2;
        dataHard_V_47_fu_454 <= dataHard_V_121_fu_1504_p2;
        dataHard_V_48_fu_458 <= dataHard_V_122_fu_1508_p2;
        dataHard_V_49_fu_462 <= dataHard_V_123_fu_1512_p2;
        dataHard_V_50_fu_466 <= dataHard_V_124_fu_1517_p2;
        dataHard_V_51_fu_470 <= dataHard_V_125_fu_1522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln22_reg_3072_pp0_iter1_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dataHard_V_52_fu_474 <= dataHard_V_104_reg_3076;
        dataHard_V_53_fu_478 <= dataHard_V_111_reg_3107;
        dataHard_V_54_fu_482 <= dataHard_V_117_fu_1492_p2;
        dataHard_V_55_fu_486 <= dataHard_V_105_reg_3092;
        dataHard_V_56_fu_490 <= dataHard_V_118_reg_3124;
        dataHard_V_57_fu_494 <= dataHard_V_119_fu_1496_p2;
        dataHard_V_58_fu_498 <= dataHard_V_120_fu_1500_p2;
        dataHard_V_59_fu_502 <= dataHard_V_107_fu_1488_p2;
        dataHard_V_60_fu_506 <= dataHard_V_121_fu_1504_p2;
        dataHard_V_61_fu_510 <= dataHard_V_122_fu_1508_p2;
        dataHard_V_62_fu_514 <= dataHard_V_123_fu_1512_p2;
        dataHard_V_63_fu_518 <= dataHard_V_124_fu_1517_p2;
        dataHard_V_64_fu_522 <= dataHard_V_125_fu_1522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln22_reg_3072_pp0_iter1_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dataHard_V_65_fu_526 <= dataHard_V_104_reg_3076;
        dataHard_V_66_fu_530 <= dataHard_V_111_reg_3107;
        dataHard_V_67_fu_534 <= dataHard_V_117_fu_1492_p2;
        dataHard_V_68_fu_538 <= dataHard_V_105_reg_3092;
        dataHard_V_69_fu_542 <= dataHard_V_118_reg_3124;
        dataHard_V_70_fu_546 <= dataHard_V_119_fu_1496_p2;
        dataHard_V_71_fu_550 <= dataHard_V_120_fu_1500_p2;
        dataHard_V_72_fu_554 <= dataHard_V_107_fu_1488_p2;
        dataHard_V_73_fu_558 <= dataHard_V_121_fu_1504_p2;
        dataHard_V_74_fu_562 <= dataHard_V_122_fu_1508_p2;
        dataHard_V_75_fu_566 <= dataHard_V_123_fu_1512_p2;
        dataHard_V_76_fu_570 <= dataHard_V_124_fu_1517_p2;
        dataHard_V_77_fu_574 <= dataHard_V_125_fu_1522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln22_reg_3072_pp0_iter1_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dataHard_V_78_fu_578 <= dataHard_V_104_reg_3076;
        dataHard_V_79_fu_582 <= dataHard_V_111_reg_3107;
        dataHard_V_80_fu_586 <= dataHard_V_117_fu_1492_p2;
        dataHard_V_81_fu_590 <= dataHard_V_105_reg_3092;
        dataHard_V_82_fu_594 <= dataHard_V_118_reg_3124;
        dataHard_V_83_fu_598 <= dataHard_V_119_fu_1496_p2;
        dataHard_V_84_fu_602 <= dataHard_V_120_fu_1500_p2;
        dataHard_V_85_fu_606 <= dataHard_V_107_fu_1488_p2;
        dataHard_V_86_fu_610 <= dataHard_V_121_fu_1504_p2;
        dataHard_V_87_fu_614 <= dataHard_V_122_fu_1508_p2;
        dataHard_V_88_fu_618 <= dataHard_V_123_fu_1512_p2;
        dataHard_V_89_fu_622 <= dataHard_V_124_fu_1517_p2;
        dataHard_V_90_fu_626 <= dataHard_V_125_fu_1522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_fu_1436_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln22_reg_3072 <= trunc_ln22_fu_1453_p1;
    end
end

always @ (*) begin
    if (((icmp_ln20_fu_1436_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_262;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_100_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_100_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_101_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_101_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_102_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_102_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_103_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_103_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_10_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_11_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_12_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_13_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_14_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_15_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_16_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_17_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_18_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_19_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_1_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_20_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_21_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_22_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_23_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_24_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_25_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_26_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_27_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_28_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_29_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_2_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_30_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_31_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_32_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_33_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_34_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_35_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_36_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_37_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_38_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_39_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_3_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_40_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_41_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_42_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_43_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_44_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_45_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_46_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_47_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_47_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_48_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_48_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_49_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_49_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_4_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_50_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_50_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_51_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_51_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_52_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_52_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_53_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_53_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_54_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_54_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_55_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_55_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_56_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_56_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_57_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_57_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_58_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_58_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_59_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_59_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_5_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_60_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_60_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_61_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_61_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_62_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_62_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_63_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_64_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_64_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_65_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_65_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_66_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_66_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_67_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_67_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_68_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_68_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_69_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_69_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_6_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_70_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_70_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_71_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_71_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_72_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_72_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_73_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_73_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_74_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_74_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_75_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_75_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_76_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_76_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_77_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_77_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_78_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_78_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_79_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_79_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_7_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_80_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_80_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_81_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_81_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_82_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_82_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_83_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_83_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_84_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_84_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_85_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_85_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_86_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_86_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_87_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_87_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_88_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_88_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_89_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_89_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_8_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_90_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_90_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_91_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_91_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_92_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_92_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_93_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_93_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_94_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_94_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_95_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_95_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_96_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_96_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_97_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_97_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_98_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_98_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_99_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_99_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_9_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_reg_3063 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataHard_V_out_ap_vld = 1'b1;
    end else begin
        dataHard_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dataPoints_ce0 = 1'b1;
    end else begin
        dataPoints_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln20_fu_1442_p2 = (ap_sig_allocacmp_i_2 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign dataHard_V_100_out = dataHard_V_100_fu_666;

assign dataHard_V_101_out = dataHard_V_101_fu_670;

assign dataHard_V_102_out = dataHard_V_102_fu_674;

assign dataHard_V_103_out = dataHard_V_103_fu_678;

assign dataHard_V_104_fu_1462_p1 = dataPoints_q0[31:0];

assign dataHard_V_10_out = dataHard_V_10_fu_306;

assign dataHard_V_118_fu_1482_p0 = {{dataPoints_q0[63:32]}};

assign dataHard_V_118_fu_1482_p1 = {{dataPoints_q0[63:32]}};

assign dataHard_V_11_out = dataHard_V_11_fu_310;

assign dataHard_V_12_out = dataHard_V_12_fu_314;

assign dataHard_V_13_out = dataHard_V_13_fu_318;

assign dataHard_V_14_out = dataHard_V_14_fu_322;

assign dataHard_V_15_out = dataHard_V_15_fu_326;

assign dataHard_V_16_out = dataHard_V_16_fu_330;

assign dataHard_V_17_out = dataHard_V_17_fu_334;

assign dataHard_V_18_out = dataHard_V_18_fu_338;

assign dataHard_V_19_out = dataHard_V_19_fu_342;

assign dataHard_V_1_out = dataHard_V_1_fu_270;

assign dataHard_V_20_out = dataHard_V_20_fu_346;

assign dataHard_V_21_out = dataHard_V_21_fu_350;

assign dataHard_V_22_out = dataHard_V_22_fu_354;

assign dataHard_V_23_out = dataHard_V_23_fu_358;

assign dataHard_V_24_out = dataHard_V_24_fu_362;

assign dataHard_V_25_out = dataHard_V_25_fu_366;

assign dataHard_V_26_out = dataHard_V_26_fu_370;

assign dataHard_V_27_out = dataHard_V_27_fu_374;

assign dataHard_V_28_out = dataHard_V_28_fu_378;

assign dataHard_V_29_out = dataHard_V_29_fu_382;

assign dataHard_V_2_out = dataHard_V_2_fu_274;

assign dataHard_V_30_out = dataHard_V_30_fu_386;

assign dataHard_V_31_out = dataHard_V_31_fu_390;

assign dataHard_V_32_out = dataHard_V_32_fu_394;

assign dataHard_V_33_out = dataHard_V_33_fu_398;

assign dataHard_V_34_out = dataHard_V_34_fu_402;

assign dataHard_V_35_out = dataHard_V_35_fu_406;

assign dataHard_V_36_out = dataHard_V_36_fu_410;

assign dataHard_V_37_out = dataHard_V_37_fu_414;

assign dataHard_V_38_out = dataHard_V_38_fu_418;

assign dataHard_V_39_out = dataHard_V_39_fu_422;

assign dataHard_V_3_out = dataHard_V_3_fu_278;

assign dataHard_V_40_out = dataHard_V_40_fu_426;

assign dataHard_V_41_out = dataHard_V_41_fu_430;

assign dataHard_V_42_out = dataHard_V_42_fu_434;

assign dataHard_V_43_out = dataHard_V_43_fu_438;

assign dataHard_V_44_out = dataHard_V_44_fu_442;

assign dataHard_V_45_out = dataHard_V_45_fu_446;

assign dataHard_V_46_out = dataHard_V_46_fu_450;

assign dataHard_V_47_out = dataHard_V_47_fu_454;

assign dataHard_V_48_out = dataHard_V_48_fu_458;

assign dataHard_V_49_out = dataHard_V_49_fu_462;

assign dataHard_V_4_out = dataHard_V_4_fu_282;

assign dataHard_V_50_out = dataHard_V_50_fu_466;

assign dataHard_V_51_out = dataHard_V_51_fu_470;

assign dataHard_V_52_out = dataHard_V_52_fu_474;

assign dataHard_V_53_out = dataHard_V_53_fu_478;

assign dataHard_V_54_out = dataHard_V_54_fu_482;

assign dataHard_V_55_out = dataHard_V_55_fu_486;

assign dataHard_V_56_out = dataHard_V_56_fu_490;

assign dataHard_V_57_out = dataHard_V_57_fu_494;

assign dataHard_V_58_out = dataHard_V_58_fu_498;

assign dataHard_V_59_out = dataHard_V_59_fu_502;

assign dataHard_V_5_out = dataHard_V_5_fu_286;

assign dataHard_V_60_out = dataHard_V_60_fu_506;

assign dataHard_V_61_out = dataHard_V_61_fu_510;

assign dataHard_V_62_out = dataHard_V_62_fu_514;

assign dataHard_V_63_out = dataHard_V_63_fu_518;

assign dataHard_V_64_out = dataHard_V_64_fu_522;

assign dataHard_V_65_out = dataHard_V_65_fu_526;

assign dataHard_V_66_out = dataHard_V_66_fu_530;

assign dataHard_V_67_out = dataHard_V_67_fu_534;

assign dataHard_V_68_out = dataHard_V_68_fu_538;

assign dataHard_V_69_out = dataHard_V_69_fu_542;

assign dataHard_V_6_out = dataHard_V_6_fu_290;

assign dataHard_V_70_out = dataHard_V_70_fu_546;

assign dataHard_V_71_out = dataHard_V_71_fu_550;

assign dataHard_V_72_out = dataHard_V_72_fu_554;

assign dataHard_V_73_out = dataHard_V_73_fu_558;

assign dataHard_V_74_out = dataHard_V_74_fu_562;

assign dataHard_V_75_out = dataHard_V_75_fu_566;

assign dataHard_V_76_out = dataHard_V_76_fu_570;

assign dataHard_V_77_out = dataHard_V_77_fu_574;

assign dataHard_V_78_out = dataHard_V_78_fu_578;

assign dataHard_V_79_out = dataHard_V_79_fu_582;

assign dataHard_V_7_out = dataHard_V_7_fu_294;

assign dataHard_V_80_out = dataHard_V_80_fu_586;

assign dataHard_V_81_out = dataHard_V_81_fu_590;

assign dataHard_V_82_out = dataHard_V_82_fu_594;

assign dataHard_V_83_out = dataHard_V_83_fu_598;

assign dataHard_V_84_out = dataHard_V_84_fu_602;

assign dataHard_V_85_out = dataHard_V_85_fu_606;

assign dataHard_V_86_out = dataHard_V_86_fu_610;

assign dataHard_V_87_out = dataHard_V_87_fu_614;

assign dataHard_V_88_out = dataHard_V_88_fu_618;

assign dataHard_V_89_out = dataHard_V_89_fu_622;

assign dataHard_V_8_out = dataHard_V_8_fu_298;

assign dataHard_V_90_out = dataHard_V_90_fu_626;

assign dataHard_V_91_out = dataHard_V_91_fu_630;

assign dataHard_V_92_out = dataHard_V_92_fu_634;

assign dataHard_V_93_out = dataHard_V_93_fu_638;

assign dataHard_V_94_out = dataHard_V_94_fu_642;

assign dataHard_V_95_out = dataHard_V_95_fu_646;

assign dataHard_V_96_out = dataHard_V_96_fu_650;

assign dataHard_V_97_out = dataHard_V_97_fu_654;

assign dataHard_V_98_out = dataHard_V_98_fu_658;

assign dataHard_V_99_out = dataHard_V_99_fu_662;

assign dataHard_V_9_out = dataHard_V_9_fu_302;

assign dataHard_V_out = dataHard_V_fu_266;

assign dataPoints_address0 = zext_ln20_fu_1448_p1;

assign icmp_ln20_fu_1436_p2 = ((ap_sig_allocacmp_i_2 == 4'd8) ? 1'b1 : 1'b0);

assign trunc_ln22_fu_1453_p1 = ap_sig_allocacmp_i_2[2:0];

assign zext_ln20_fu_1448_p1 = ap_sig_allocacmp_i_2;

endmodule //ellipse_solver_ellipse_solver_Pipeline_first_loop
