// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ellipse_solver_ellipse_solver,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.840000,HLS_SYN_LAT=49,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3959,HLS_SYN_LUT=1990,HLS_VERSION=2022_2}" *)

module ellipse_solver (
        ap_clk,
        ap_rst_n,
        dataPoints_address0,
        dataPoints_ce0,
        dataPoints_q0,
        matrix_address0,
        matrix_ce0,
        matrix_we0,
        matrix_d0,
        matrix_address1,
        matrix_ce1,
        matrix_we1,
        matrix_d1,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [2:0] dataPoints_address0;
output   dataPoints_ce0;
input  [63:0] dataPoints_q0;
output  [4:0] matrix_address0;
output   matrix_ce0;
output   matrix_we0;
output  [31:0] matrix_d0;
output  [4:0] matrix_address1;
output   matrix_ce1;
output   matrix_we1;
output  [31:0] matrix_d1;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg[4:0] matrix_address0;
reg matrix_ce0;
reg matrix_we0;
reg[31:0] matrix_d0;
reg[4:0] matrix_address1;
reg matrix_ce1;
reg matrix_we1;
reg[31:0] matrix_d1;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire    grp_ellipse_solver_Pipeline_1_fu_892_ap_start;
wire    grp_ellipse_solver_Pipeline_1_fu_892_ap_done;
wire    grp_ellipse_solver_Pipeline_1_fu_892_ap_idle;
wire    grp_ellipse_solver_Pipeline_1_fu_892_ap_ready;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_12_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_12_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_11_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_11_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_10_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_10_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_9_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_9_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_8_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_8_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_7_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_7_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_6_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_6_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_5_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_5_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_4_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_4_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_3_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_3_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_2_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_2_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_1_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_1_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_1_fu_892_outData_out;
wire    grp_ellipse_solver_Pipeline_1_fu_892_outData_out_ap_vld;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_start;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_done;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_idle;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_ready;
wire   [2:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataPoints_address0;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataPoints_ce0;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_103_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_103_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_102_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_102_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_101_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_101_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_100_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_100_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_99_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_99_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_98_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_98_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_97_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_97_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_96_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_96_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_95_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_95_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_94_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_94_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_93_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_93_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_92_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_92_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_91_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_91_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_90_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_90_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_89_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_89_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_88_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_88_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_87_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_87_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_86_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_86_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_85_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_85_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_84_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_84_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_83_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_83_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_82_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_82_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_81_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_81_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_80_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_80_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_79_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_79_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_78_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_78_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_77_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_77_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_76_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_76_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_75_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_75_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_74_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_74_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_73_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_73_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_72_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_72_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_71_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_71_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_70_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_70_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_69_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_69_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_68_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_68_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_67_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_67_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_66_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_66_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_65_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_65_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_64_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_64_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_63_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_63_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_62_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_62_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_61_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_61_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_60_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_60_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_59_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_59_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_58_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_58_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_57_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_57_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_56_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_56_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_55_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_55_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_54_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_54_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_53_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_53_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_52_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_52_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_51_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_51_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_50_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_50_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_49_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_49_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_48_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_48_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_47_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_47_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_46_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_46_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_45_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_45_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_44_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_44_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_43_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_43_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_42_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_42_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_41_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_41_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_40_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_40_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_39_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_39_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_38_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_38_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_37_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_37_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_36_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_36_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_35_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_35_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_34_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_34_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_33_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_33_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_32_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_32_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_31_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_31_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_30_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_30_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_29_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_29_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_28_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_28_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_27_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_27_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_26_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_26_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_25_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_25_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_24_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_24_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_23_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_23_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_22_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_22_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_21_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_21_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_20_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_20_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_19_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_19_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_18_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_18_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_17_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_17_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_16_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_16_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_15_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_15_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_14_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_14_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_13_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_13_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_12_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_12_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_11_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_11_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_10_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_10_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_9_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_9_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_8_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_8_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_7_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_7_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_6_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_6_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_5_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_5_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_4_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_4_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_3_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_3_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_2_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_2_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_1_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_1_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_out;
wire    grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_out_ap_vld;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_start;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_done;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_idle;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_ready;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_38_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_38_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_37_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_37_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_36_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_36_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_35_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_35_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_34_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_34_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_33_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_33_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_32_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_32_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_31_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_31_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_30_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_30_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_29_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_29_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_28_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_28_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_27_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_27_out_ap_vld;
wire   [31:0] grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_26_out;
wire    grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_26_out_ap_vld;
reg    grp_ellipse_solver_Pipeline_1_fu_892_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_start_reg;
reg    grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire   [31:0] sub_ln52_fu_1644_p2;
wire   [31:0] sub_ln58_fu_1662_p2;
wire   [31:0] sub_ln64_fu_1680_p2;
wire   [31:0] sub_ln70_fu_1691_p2;
wire   [31:0] sub_ln76_fu_1697_p2;
reg   [18:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 grp_ellipse_solver_Pipeline_1_fu_892_ap_start_reg = 1'b0;
#0 grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_start_reg = 1'b0;
#0 grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_start_reg = 1'b0;
end

ellipse_solver_ellipse_solver_Pipeline_1 grp_ellipse_solver_Pipeline_1_fu_892(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ellipse_solver_Pipeline_1_fu_892_ap_start),
    .ap_done(grp_ellipse_solver_Pipeline_1_fu_892_ap_done),
    .ap_idle(grp_ellipse_solver_Pipeline_1_fu_892_ap_idle),
    .ap_ready(grp_ellipse_solver_Pipeline_1_fu_892_ap_ready),
    .outData_12_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_12_out),
    .outData_12_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_12_out_ap_vld),
    .outData_11_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_11_out),
    .outData_11_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_11_out_ap_vld),
    .outData_10_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_10_out),
    .outData_10_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_10_out_ap_vld),
    .outData_9_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_9_out),
    .outData_9_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_9_out_ap_vld),
    .outData_8_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_8_out),
    .outData_8_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_8_out_ap_vld),
    .outData_7_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_7_out),
    .outData_7_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_7_out_ap_vld),
    .outData_6_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_6_out),
    .outData_6_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_6_out_ap_vld),
    .outData_5_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_5_out),
    .outData_5_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_5_out_ap_vld),
    .outData_4_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_4_out),
    .outData_4_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_4_out_ap_vld),
    .outData_3_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_3_out),
    .outData_3_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_3_out_ap_vld),
    .outData_2_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_2_out),
    .outData_2_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_2_out_ap_vld),
    .outData_1_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_1_out),
    .outData_1_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_1_out_ap_vld),
    .outData_out(grp_ellipse_solver_Pipeline_1_fu_892_outData_out),
    .outData_out_ap_vld(grp_ellipse_solver_Pipeline_1_fu_892_outData_out_ap_vld)
);

ellipse_solver_ellipse_solver_Pipeline_first_loop grp_ellipse_solver_Pipeline_first_loop_fu_909(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_start),
    .ap_done(grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_done),
    .ap_idle(grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_idle),
    .ap_ready(grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_ready),
    .dataPoints_address0(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataPoints_address0),
    .dataPoints_ce0(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataPoints_ce0),
    .dataPoints_q0(dataPoints_q0),
    .dataHard_V_103_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_103_out),
    .dataHard_V_103_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_103_out_ap_vld),
    .dataHard_V_102_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_102_out),
    .dataHard_V_102_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_102_out_ap_vld),
    .dataHard_V_101_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_101_out),
    .dataHard_V_101_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_101_out_ap_vld),
    .dataHard_V_100_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_100_out),
    .dataHard_V_100_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_100_out_ap_vld),
    .dataHard_V_99_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_99_out),
    .dataHard_V_99_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_99_out_ap_vld),
    .dataHard_V_98_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_98_out),
    .dataHard_V_98_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_98_out_ap_vld),
    .dataHard_V_97_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_97_out),
    .dataHard_V_97_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_97_out_ap_vld),
    .dataHard_V_96_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_96_out),
    .dataHard_V_96_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_96_out_ap_vld),
    .dataHard_V_95_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_95_out),
    .dataHard_V_95_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_95_out_ap_vld),
    .dataHard_V_94_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_94_out),
    .dataHard_V_94_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_94_out_ap_vld),
    .dataHard_V_93_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_93_out),
    .dataHard_V_93_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_93_out_ap_vld),
    .dataHard_V_92_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_92_out),
    .dataHard_V_92_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_92_out_ap_vld),
    .dataHard_V_91_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_91_out),
    .dataHard_V_91_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_91_out_ap_vld),
    .dataHard_V_90_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_90_out),
    .dataHard_V_90_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_90_out_ap_vld),
    .dataHard_V_89_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_89_out),
    .dataHard_V_89_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_89_out_ap_vld),
    .dataHard_V_88_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_88_out),
    .dataHard_V_88_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_88_out_ap_vld),
    .dataHard_V_87_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_87_out),
    .dataHard_V_87_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_87_out_ap_vld),
    .dataHard_V_86_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_86_out),
    .dataHard_V_86_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_86_out_ap_vld),
    .dataHard_V_85_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_85_out),
    .dataHard_V_85_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_85_out_ap_vld),
    .dataHard_V_84_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_84_out),
    .dataHard_V_84_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_84_out_ap_vld),
    .dataHard_V_83_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_83_out),
    .dataHard_V_83_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_83_out_ap_vld),
    .dataHard_V_82_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_82_out),
    .dataHard_V_82_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_82_out_ap_vld),
    .dataHard_V_81_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_81_out),
    .dataHard_V_81_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_81_out_ap_vld),
    .dataHard_V_80_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_80_out),
    .dataHard_V_80_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_80_out_ap_vld),
    .dataHard_V_79_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_79_out),
    .dataHard_V_79_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_79_out_ap_vld),
    .dataHard_V_78_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_78_out),
    .dataHard_V_78_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_78_out_ap_vld),
    .dataHard_V_77_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_77_out),
    .dataHard_V_77_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_77_out_ap_vld),
    .dataHard_V_76_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_76_out),
    .dataHard_V_76_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_76_out_ap_vld),
    .dataHard_V_75_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_75_out),
    .dataHard_V_75_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_75_out_ap_vld),
    .dataHard_V_74_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_74_out),
    .dataHard_V_74_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_74_out_ap_vld),
    .dataHard_V_73_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_73_out),
    .dataHard_V_73_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_73_out_ap_vld),
    .dataHard_V_72_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_72_out),
    .dataHard_V_72_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_72_out_ap_vld),
    .dataHard_V_71_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_71_out),
    .dataHard_V_71_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_71_out_ap_vld),
    .dataHard_V_70_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_70_out),
    .dataHard_V_70_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_70_out_ap_vld),
    .dataHard_V_69_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_69_out),
    .dataHard_V_69_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_69_out_ap_vld),
    .dataHard_V_68_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_68_out),
    .dataHard_V_68_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_68_out_ap_vld),
    .dataHard_V_67_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_67_out),
    .dataHard_V_67_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_67_out_ap_vld),
    .dataHard_V_66_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_66_out),
    .dataHard_V_66_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_66_out_ap_vld),
    .dataHard_V_65_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_65_out),
    .dataHard_V_65_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_65_out_ap_vld),
    .dataHard_V_64_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_64_out),
    .dataHard_V_64_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_64_out_ap_vld),
    .dataHard_V_63_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_63_out),
    .dataHard_V_63_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_63_out_ap_vld),
    .dataHard_V_62_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_62_out),
    .dataHard_V_62_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_62_out_ap_vld),
    .dataHard_V_61_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_61_out),
    .dataHard_V_61_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_61_out_ap_vld),
    .dataHard_V_60_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_60_out),
    .dataHard_V_60_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_60_out_ap_vld),
    .dataHard_V_59_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_59_out),
    .dataHard_V_59_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_59_out_ap_vld),
    .dataHard_V_58_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_58_out),
    .dataHard_V_58_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_58_out_ap_vld),
    .dataHard_V_57_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_57_out),
    .dataHard_V_57_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_57_out_ap_vld),
    .dataHard_V_56_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_56_out),
    .dataHard_V_56_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_56_out_ap_vld),
    .dataHard_V_55_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_55_out),
    .dataHard_V_55_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_55_out_ap_vld),
    .dataHard_V_54_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_54_out),
    .dataHard_V_54_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_54_out_ap_vld),
    .dataHard_V_53_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_53_out),
    .dataHard_V_53_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_53_out_ap_vld),
    .dataHard_V_52_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_52_out),
    .dataHard_V_52_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_52_out_ap_vld),
    .dataHard_V_51_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_51_out),
    .dataHard_V_51_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_51_out_ap_vld),
    .dataHard_V_50_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_50_out),
    .dataHard_V_50_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_50_out_ap_vld),
    .dataHard_V_49_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_49_out),
    .dataHard_V_49_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_49_out_ap_vld),
    .dataHard_V_48_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_48_out),
    .dataHard_V_48_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_48_out_ap_vld),
    .dataHard_V_47_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_47_out),
    .dataHard_V_47_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_47_out_ap_vld),
    .dataHard_V_46_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_46_out),
    .dataHard_V_46_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_46_out_ap_vld),
    .dataHard_V_45_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_45_out),
    .dataHard_V_45_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_45_out_ap_vld),
    .dataHard_V_44_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_44_out),
    .dataHard_V_44_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_44_out_ap_vld),
    .dataHard_V_43_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_43_out),
    .dataHard_V_43_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_43_out_ap_vld),
    .dataHard_V_42_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_42_out),
    .dataHard_V_42_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_42_out_ap_vld),
    .dataHard_V_41_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_41_out),
    .dataHard_V_41_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_41_out_ap_vld),
    .dataHard_V_40_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_40_out),
    .dataHard_V_40_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_40_out_ap_vld),
    .dataHard_V_39_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_39_out),
    .dataHard_V_39_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_39_out_ap_vld),
    .dataHard_V_38_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_38_out),
    .dataHard_V_38_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_38_out_ap_vld),
    .dataHard_V_37_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_37_out),
    .dataHard_V_37_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_37_out_ap_vld),
    .dataHard_V_36_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_36_out),
    .dataHard_V_36_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_36_out_ap_vld),
    .dataHard_V_35_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_35_out),
    .dataHard_V_35_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_35_out_ap_vld),
    .dataHard_V_34_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_34_out),
    .dataHard_V_34_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_34_out_ap_vld),
    .dataHard_V_33_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_33_out),
    .dataHard_V_33_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_33_out_ap_vld),
    .dataHard_V_32_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_32_out),
    .dataHard_V_32_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_32_out_ap_vld),
    .dataHard_V_31_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_31_out),
    .dataHard_V_31_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_31_out_ap_vld),
    .dataHard_V_30_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_30_out),
    .dataHard_V_30_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_30_out_ap_vld),
    .dataHard_V_29_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_29_out),
    .dataHard_V_29_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_29_out_ap_vld),
    .dataHard_V_28_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_28_out),
    .dataHard_V_28_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_28_out_ap_vld),
    .dataHard_V_27_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_27_out),
    .dataHard_V_27_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_27_out_ap_vld),
    .dataHard_V_26_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_26_out),
    .dataHard_V_26_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_26_out_ap_vld),
    .dataHard_V_25_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_25_out),
    .dataHard_V_25_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_25_out_ap_vld),
    .dataHard_V_24_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_24_out),
    .dataHard_V_24_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_24_out_ap_vld),
    .dataHard_V_23_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_23_out),
    .dataHard_V_23_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_23_out_ap_vld),
    .dataHard_V_22_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_22_out),
    .dataHard_V_22_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_22_out_ap_vld),
    .dataHard_V_21_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_21_out),
    .dataHard_V_21_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_21_out_ap_vld),
    .dataHard_V_20_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_20_out),
    .dataHard_V_20_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_20_out_ap_vld),
    .dataHard_V_19_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_19_out),
    .dataHard_V_19_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_19_out_ap_vld),
    .dataHard_V_18_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_18_out),
    .dataHard_V_18_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_18_out_ap_vld),
    .dataHard_V_17_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_17_out),
    .dataHard_V_17_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_17_out_ap_vld),
    .dataHard_V_16_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_16_out),
    .dataHard_V_16_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_16_out_ap_vld),
    .dataHard_V_15_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_15_out),
    .dataHard_V_15_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_15_out_ap_vld),
    .dataHard_V_14_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_14_out),
    .dataHard_V_14_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_14_out_ap_vld),
    .dataHard_V_13_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_13_out),
    .dataHard_V_13_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_13_out_ap_vld),
    .dataHard_V_12_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_12_out),
    .dataHard_V_12_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_12_out_ap_vld),
    .dataHard_V_11_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_11_out),
    .dataHard_V_11_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_11_out_ap_vld),
    .dataHard_V_10_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_10_out),
    .dataHard_V_10_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_10_out_ap_vld),
    .dataHard_V_9_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_9_out),
    .dataHard_V_9_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_9_out_ap_vld),
    .dataHard_V_8_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_8_out),
    .dataHard_V_8_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_8_out_ap_vld),
    .dataHard_V_7_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_7_out),
    .dataHard_V_7_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_7_out_ap_vld),
    .dataHard_V_6_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_6_out),
    .dataHard_V_6_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_6_out_ap_vld),
    .dataHard_V_5_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_5_out),
    .dataHard_V_5_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_5_out_ap_vld),
    .dataHard_V_4_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_4_out),
    .dataHard_V_4_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_4_out_ap_vld),
    .dataHard_V_3_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_3_out),
    .dataHard_V_3_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_3_out_ap_vld),
    .dataHard_V_2_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_2_out),
    .dataHard_V_2_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_2_out_ap_vld),
    .dataHard_V_1_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_1_out),
    .dataHard_V_1_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_1_out_ap_vld),
    .dataHard_V_out(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_out),
    .dataHard_V_out_ap_vld(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_out_ap_vld)
);

ellipse_solver_ellipse_solver_Pipeline_second_loop grp_ellipse_solver_Pipeline_second_loop_fu_1019(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_start),
    .ap_done(grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_done),
    .ap_idle(grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_idle),
    .ap_ready(grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_ready),
    .outData_12_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_12_out),
    .outData_11_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_11_out),
    .outData_10_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_10_out),
    .outData_9_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_9_out),
    .outData_8_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_8_out),
    .outData_7_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_7_out),
    .outData_6_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_6_out),
    .outData_5_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_5_out),
    .outData_4_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_4_out),
    .outData_3_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_3_out),
    .outData_2_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_2_out),
    .outData_1_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_1_out),
    .outData_reload(grp_ellipse_solver_Pipeline_1_fu_892_outData_out),
    .dataHard_V_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_out),
    .dataHard_V_1_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_1_out),
    .dataHard_V_2_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_2_out),
    .dataHard_V_3_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_3_out),
    .dataHard_V_4_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_4_out),
    .dataHard_V_5_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_5_out),
    .dataHard_V_6_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_6_out),
    .dataHard_V_7_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_7_out),
    .dataHard_V_8_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_8_out),
    .dataHard_V_9_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_9_out),
    .dataHard_V_10_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_10_out),
    .dataHard_V_11_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_11_out),
    .dataHard_V_12_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_12_out),
    .dataHard_V_13_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_13_out),
    .dataHard_V_14_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_14_out),
    .dataHard_V_15_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_15_out),
    .dataHard_V_16_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_16_out),
    .dataHard_V_17_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_17_out),
    .dataHard_V_18_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_18_out),
    .dataHard_V_19_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_19_out),
    .dataHard_V_20_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_20_out),
    .dataHard_V_21_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_21_out),
    .dataHard_V_22_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_22_out),
    .dataHard_V_23_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_23_out),
    .dataHard_V_24_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_24_out),
    .dataHard_V_25_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_25_out),
    .dataHard_V_26_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_26_out),
    .dataHard_V_27_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_27_out),
    .dataHard_V_28_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_28_out),
    .dataHard_V_29_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_29_out),
    .dataHard_V_30_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_30_out),
    .dataHard_V_31_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_31_out),
    .dataHard_V_32_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_32_out),
    .dataHard_V_33_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_33_out),
    .dataHard_V_34_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_34_out),
    .dataHard_V_35_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_35_out),
    .dataHard_V_36_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_36_out),
    .dataHard_V_37_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_37_out),
    .dataHard_V_38_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_38_out),
    .dataHard_V_39_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_39_out),
    .dataHard_V_40_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_40_out),
    .dataHard_V_41_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_41_out),
    .dataHard_V_42_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_42_out),
    .dataHard_V_43_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_43_out),
    .dataHard_V_44_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_44_out),
    .dataHard_V_45_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_45_out),
    .dataHard_V_46_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_46_out),
    .dataHard_V_47_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_47_out),
    .dataHard_V_48_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_48_out),
    .dataHard_V_49_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_49_out),
    .dataHard_V_50_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_50_out),
    .dataHard_V_51_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_51_out),
    .dataHard_V_52_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_52_out),
    .dataHard_V_53_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_53_out),
    .dataHard_V_54_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_54_out),
    .dataHard_V_55_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_55_out),
    .dataHard_V_56_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_56_out),
    .dataHard_V_57_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_57_out),
    .dataHard_V_58_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_58_out),
    .dataHard_V_59_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_59_out),
    .dataHard_V_60_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_60_out),
    .dataHard_V_61_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_61_out),
    .dataHard_V_62_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_62_out),
    .dataHard_V_63_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_63_out),
    .dataHard_V_64_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_64_out),
    .dataHard_V_65_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_65_out),
    .dataHard_V_66_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_66_out),
    .dataHard_V_67_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_67_out),
    .dataHard_V_68_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_68_out),
    .dataHard_V_69_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_69_out),
    .dataHard_V_70_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_70_out),
    .dataHard_V_71_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_71_out),
    .dataHard_V_72_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_72_out),
    .dataHard_V_73_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_73_out),
    .dataHard_V_74_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_74_out),
    .dataHard_V_75_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_75_out),
    .dataHard_V_76_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_76_out),
    .dataHard_V_77_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_77_out),
    .dataHard_V_78_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_78_out),
    .dataHard_V_79_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_79_out),
    .dataHard_V_80_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_80_out),
    .dataHard_V_81_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_81_out),
    .dataHard_V_82_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_82_out),
    .dataHard_V_83_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_83_out),
    .dataHard_V_84_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_84_out),
    .dataHard_V_85_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_85_out),
    .dataHard_V_86_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_86_out),
    .dataHard_V_87_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_87_out),
    .dataHard_V_88_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_88_out),
    .dataHard_V_89_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_89_out),
    .dataHard_V_90_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_90_out),
    .dataHard_V_91_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_91_out),
    .dataHard_V_92_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_92_out),
    .dataHard_V_93_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_93_out),
    .dataHard_V_94_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_94_out),
    .dataHard_V_95_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_95_out),
    .dataHard_V_96_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_96_out),
    .dataHard_V_97_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_97_out),
    .dataHard_V_98_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_98_out),
    .dataHard_V_99_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_99_out),
    .dataHard_V_100_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_100_out),
    .dataHard_V_101_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_101_out),
    .dataHard_V_102_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_102_out),
    .dataHard_V_103_reload(grp_ellipse_solver_Pipeline_first_loop_fu_909_dataHard_V_103_out),
    .outData_38_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_38_out),
    .outData_38_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_38_out_ap_vld),
    .outData_37_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_37_out),
    .outData_37_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_37_out_ap_vld),
    .outData_36_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_36_out),
    .outData_36_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_36_out_ap_vld),
    .outData_35_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_35_out),
    .outData_35_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_35_out_ap_vld),
    .outData_34_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_34_out),
    .outData_34_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_34_out_ap_vld),
    .outData_33_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_33_out),
    .outData_33_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_33_out_ap_vld),
    .outData_32_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_32_out),
    .outData_32_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_32_out_ap_vld),
    .outData_31_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_31_out),
    .outData_31_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_31_out_ap_vld),
    .outData_30_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_30_out),
    .outData_30_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_30_out_ap_vld),
    .outData_29_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_29_out),
    .outData_29_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_29_out_ap_vld),
    .outData_28_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_28_out),
    .outData_28_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_28_out_ap_vld),
    .outData_27_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_27_out),
    .outData_27_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_27_out_ap_vld),
    .outData_26_out(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_26_out),
    .outData_26_out_ap_vld(grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_26_out_ap_vld)
);

ellipse_solver_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ellipse_solver_Pipeline_1_fu_892_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_ellipse_solver_Pipeline_1_fu_892_ap_start_reg <= 1'b1;
        end else if ((grp_ellipse_solver_Pipeline_1_fu_892_ap_ready == 1'b1)) begin
            grp_ellipse_solver_Pipeline_1_fu_892_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_start_reg <= 1'b1;
        end else if ((grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_ready == 1'b1)) begin
            grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_start_reg <= 1'b1;
        end else if ((grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_ready == 1'b1)) begin
            grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_start_reg <= 1'b0;
        end
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        matrix_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        matrix_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        matrix_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        matrix_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        matrix_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        matrix_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        matrix_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        matrix_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        matrix_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        matrix_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        matrix_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrix_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        matrix_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        matrix_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        matrix_address0 = 64'd28;
    end else begin
        matrix_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        matrix_address1 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        matrix_address1 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        matrix_address1 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        matrix_address1 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        matrix_address1 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        matrix_address1 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        matrix_address1 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        matrix_address1 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        matrix_address1 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        matrix_address1 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        matrix_address1 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        matrix_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrix_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        matrix_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        matrix_address1 = 64'd0;
    end else begin
        matrix_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        matrix_ce0 = 1'b1;
    end else begin
        matrix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        matrix_ce1 = 1'b1;
    end else begin
        matrix_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        matrix_d0 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_27_out;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        matrix_d0 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_34_out;
    end else if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state13))) begin
        matrix_d0 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_26_out;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        matrix_d0 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_29_out;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state10))) begin
        matrix_d0 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_28_out;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        matrix_d0 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_31_out;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state7))) begin
        matrix_d0 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_30_out;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6))) begin
        matrix_d0 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_32_out;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5))) begin
        matrix_d0 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_37_out;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        matrix_d0 = 32'd8;
    end else begin
        matrix_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        matrix_d1 = sub_ln76_fu_1697_p2;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        matrix_d1 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_27_out;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        matrix_d1 = sub_ln70_fu_1691_p2;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        matrix_d1 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_30_out;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        matrix_d1 = sub_ln64_fu_1680_p2;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12))) begin
        matrix_d1 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_28_out;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        matrix_d1 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_31_out;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        matrix_d1 = sub_ln58_fu_1662_p2;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state9))) begin
        matrix_d1 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_32_out;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        matrix_d1 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_35_out;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrix_d1 = sub_ln52_fu_1644_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        matrix_d1 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_34_out;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        matrix_d1 = grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_38_out;
    end else begin
        matrix_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        matrix_we0 = 1'b1;
    end else begin
        matrix_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        matrix_we1 = 1'b1;
    end else begin
        matrix_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_done == 1'b0) | (grp_ellipse_solver_Pipeline_1_fu_892_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dataPoints_address0 = grp_ellipse_solver_Pipeline_first_loop_fu_909_dataPoints_address0;

assign dataPoints_ce0 = grp_ellipse_solver_Pipeline_first_loop_fu_909_dataPoints_ce0;

assign grp_ellipse_solver_Pipeline_1_fu_892_ap_start = grp_ellipse_solver_Pipeline_1_fu_892_ap_start_reg;

assign grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_start = grp_ellipse_solver_Pipeline_first_loop_fu_909_ap_start_reg;

assign grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_start = grp_ellipse_solver_Pipeline_second_loop_fu_1019_ap_start_reg;

assign sub_ln52_fu_1644_p2 = (32'd0 - grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_35_out);

assign sub_ln58_fu_1662_p2 = (32'd0 - grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_36_out);

assign sub_ln64_fu_1680_p2 = (32'd0 - grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_33_out);

assign sub_ln70_fu_1691_p2 = (32'd0 - grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_31_out);

assign sub_ln76_fu_1697_p2 = (32'd0 - grp_ellipse_solver_Pipeline_second_loop_fu_1019_outData_29_out);

endmodule //ellipse_solver
